            comNameTablet["values"] = (
                # Painkillers (NSAIDs & Opioids)
                "Paracetamol",
                "Ibuprofen",
                "Aspirin",
                "Diclofenac",
                "Naproxen",
                "Ketorolac",
                "Celecoxib",
                "Etoricoxib",
                "Meloxicam",
                "Indomethacin",
                "Tramadol",
                "Codeine",
                "Morphine",
                "Fentanyl",
                "Oxycodone",
                "Hydrocodone",
                "Buprenorphine",
                "Tapentadol",
                "Methadone",
                # Antibiotics
                "Amoxicillin",
                "Azithromycin",
                "Ciprofloxacin",
                "Doxycycline",
                "Cephalexin",
                "Metronidazole",
                "Erythromycin",
                "Clarithromycin",
                "Levofloxacin",
                "Penicillin",
                "Vancomycin",
                "Rifampin",
                "Linezolid",
                "Minocycline",
                "Nitrofurantoin",
                "Piperacillin/Tazobactam",
                "Meropenem",
                "Tigecycline",
                # Antivirals
                "Acyclovir",
                "Oseltamivir",
                "Ribavirin",
                "Valacyclovir",
                "Famciclovir",
                "Remdesivir",
                "Tenofovir",
                "Lamivudine",
                "Efavirenz",
                "Dolutegravir",
                "Baloxavir",
                "Darunavir",
                "Ritonavir",
                # Diabetes Medications
                "Metformin",
                "Glimepiride",
                "Pioglitazone",
                "Sitagliptin",
                "Glibenclamide",
                "Empagliflozin",
                "Canagliflozin",
                "Dapagliflozin",
                "Acarbose",
                "Repaglinide",
                "Liraglutide",
                "Semaglutide",
                "Insulin Aspart",
                "Insulin Glargine",
                # Cholesterol & Heart Medications
                "Atorvastatin",
                "Simvastatin",
                "Rosuvastatin",
                "Pravastatin",
                "Lovastatin",
                "Ezetimibe",
                "Fenofibrate",
                "Omega-3 Fatty Acids",
                "Niacin",
                "Lisinopril",
                "Losartan",
                "Amlodipine",
                "Metoprolol",
                "Propranolol",
                "Hydrochlorothiazide",
                "Furosemide",
                "Spironolactone",
                "Chlorthalidone",
                "Indapamide",
                "Ramipril",
                "Telmisartan",
                "Clonidine",
                "Ivabradine",
                "Diltiazem",
                "Verapamil",
                "Digoxin",
                # Gastric & Acid Reducers
                "Omeprazole",
                "Pantoprazole",
                "Ranitidine",
                "Esomeprazole",
                "Famotidine",
                "Lansoprazole",
                "Rabeprazole",
                "Sucralfate",
                "Magaldrate",
                "Domperidone",
                # Thyroid & Hormones
                "Levothyroxine",
                "Liothyronine",
                "Methimazole",
                "Propylthiouracil",
                "Estradiol",
                "Progesterone",
                "Testosterone",
                "DHEA",
                "Hydrocortisone",
                # Allergy & Respiratory
                "Cetirizine",
                "Loratadine",
                "Fexofenadine",
                "Diphenhydramine",
                "Chlorpheniramine",
                "Montelukast",
                "Levocetirizine",
                "Budesonide",
                "Fluticasone",
                "Salmeterol",
                "Formoterol",
                "Ipratropium",
                "Tiotropium",
                # Psychiatric & Neurological
                "Diazepam",
                "Alprazolam",
                "Lorazepam",
                "Clonazepam",
                "Buspirone",
                "Sertraline",
                "Fluoxetine",
                "Escitalopram",
                "Paroxetine",
                "Venlafaxine",
                "Risperidone",
                "Olanzapine",
                "Quetiapine",
                "Aripiprazole",
                "Haloperidol",
                "Amitriptyline",
                "Nortriptyline",
                "Duloxetine",
                "Pregabalin",
                "Gabapentin",
                # Antiepileptic & Parkinson’s
                "Carbamazepine",
                "Valproate",
                "Phenytoin",
                "Levetiracetam",
                "Topiramate",
                "Lamotrigine",
                "Ropinirole",
                "Pramipexole",
                "Selegiline",
                "Rasagiline",
                # Blood Thinners & Clotting Agents
                "Clopidogrel",
                "Warfarin",
                "Dabigatran",
                "Rivaroxaban",
                "Apixaban",
                "Enoxaparin",
                "Fondaparinux",
                "Aspirin + Clopidogrel",
                # Rheumatoid & Autoimmune
                "Methotrexate",
                "Hydroxychloroquine",
                "Sulfasalazine",
                "Leflunomide",
                "Azathioprine",
                "Mycophenolate",
                "Cyclophosphamide",
                "Adalimumab",
                # Anti-nausea & Vomiting
                "Ondansetron",
                "Metoclopramide",
                "Domperidone",
                "Prochlorperazine",
                "Granisetron",
                "Dexamethasone",
                "Aprepitant",
                # Muscle Relaxants
                "Cyclobenzaprine",
                "Baclofen",
                "Carisoprodol",
                "Tizanidine",
                "Methocarbamol",
                # Bone & Joint Health
                "Alendronate",
                "Risedronate",
                "Denosumab",
                "Calcitonin",
                "Teriparatide",
                "Vitamin D",
                "Calcium Carbonate",
                # Infectious Disease & Malaria
                "Chloroquine",
                "Hydroxychloroquine",
                "Artemether",
                "Mefloquine",
                "Primaquine",
                "Ivermectin",
                "Albendazole",
                "Mebendazole",
                "Praziquantel",
                # Cancer & Chemotherapy
                "Tamoxifen",
                "Anastrozole",
                "Letrozole",
                "Imatinib",
                "Capecitabine",
                "Cisplatin",
                "Paclitaxel",
                "Doxorubicin",
                # Miscellaneous
                "Melatonin",
                "Biotin",
                "Folic Acid",
                "Iron Tablets",
                "Zinc Tablets",
                "L-Carnitine",
                "Vitamin B Complex",
                "Multivitamins",
                "Collagen",
                "Probiotics",
                "Lutein",
                "Coenzyme Q10",
            )